name: Deploy Static Website to Heroku

on:
  push:
    branches:
      - master # O main, si tu rama principal es "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku # Desplegar a Heroku usando Heroku CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Usa el API Key de Heroku guardado en los secretos
        run: |
          git init
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git add .
          git commit -m "Deploying to Heroku"
          git push -f heroku master  # Forzar el push a Heroku
